# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kawsheek's awesome website
email: kask94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I apologise for the crude website. I am just starting down this path, so I hope I will be excused. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kawsheek.github.io" # the base hostname & protocol for your site
twitter_username: kawsheek
github_username:  kawsheek

# Build settings
markdown: kramdown
